[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "SNT"
authors = [
    {name = "André Silva", email = "Andre.Silva@astro.up.pt"}
]
description = "Tool to normalize stellar spectra"
readme = "README.rst"
requires-python = ">=3.1"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    'importlib-metadata; python_version<"3.8"',
]
dynamic = ["version"]

[tool.setuptools]
# ...
package-dir = {"" = "src"}
